Godeps/Godeps.json
mixpanel_to_redshift.go
postgres/postgres.go
redshift/README.md
redshift/redshift.go
redshift/redshift_test.go

also update the godeps to be consistent with other repos- Clever should be capitalized

allow multiple simultaneous redshifter jobs from providing different temp schemas

---

mixpanel_to_redshift.go
postgres/postgres.go

lock to v1 ahead of upcoming incompatible pathio changes

vendor pathio

---

cmd/s3_to_redshift.go
redshift/redshift.go
redshift/redshift_test.go
s3filepath/README.md
s3filepath/s3filepath.go
s3filepath/s3filepath_test.go

I need to be able to handle non-gzipped files as well for what @cgclever is working on, it was a TODO that I never got around to, although I actually prefer the smaller PR format :)

allow non-gzipped files as well

---

redshift/redshift.go
redshift/redshift_test.go

float actually gets turned into double precision

---

redshift/redshift.go
redshift/redshift_test.go

int -> integer in type mapping

---

redshift/redshift.go
redshift/redshift_test.go

this is causing my inserts to fail :(

match existing functionality by truncating too-long columns

---

redshift/README.md
redshift/redshift.go
redshift/redshift_test.go
s3filepath/s3filepath.go

Truncate columns as well

---

Makefile

The benefit is that builds will be faster

Remove go get, now have vendoring

---

Dockerfile
Godeps/Godeps.json
Makefile
README.md
vendor/github.com/Clever/s3-to-redshift/LICENSE
vendor/github.com/Clever/s3-to-redshift/redshift/README.md
vendor/github.com/Clever/s3-to-redshift/redshift/redshift.go
vendor/github.com/Clever/s3-to-redshift/s3filepath/README.md
vendor/github.com/Clever/s3-to-redshift/s3filepath/s3filepath.go
vendor/github.com/mitchellh/goamz/LICENSE

This PR was mostly autogenerated.
Changes to expect:
- removal of `*_test.go` files in /vendor
- addition of non go files in /vendor
- addtions to README.md & Makefile
**Before your merge!**:
- Please carefully check the Makefile changes
- Ensure that the build is passing
- Check that drone is using the proper image (Clever/drone-go:1.5)
Feel free to ping @natebrennand or #golang for clarification or help.
If you'd like more of an explanation please join us in #golang.

Go vendor standardization

---

cmd/s3_to_redshift.go

I realized that I wasn't closing the overall session properly, even
if I was closing the transaction. While this probably won't fix anything,
there's a decent change this will surface general connection issues via
the error passed back from the Close

Related to IP-518- close the db session properly

---

redshift/redshift.go
redshift/redshift_test.go

adding longtext option, in cases where we need to store longer texts in redshift

Add longtext column type

---

Dockerfile

Reverts Clever/s3-to-redshift#58

Revert "Up timeout"

---

README.md
redshift/redshift.go
redshift/redshift_test.go
s3_to_redshift.go

**JIRA**: https://clever.atlassian.net/browse/IP-737
**Overview**: We are updating key Pulse charts to refresh hourly (Instant Pulse!) and so as a result we'll need to modify some logic in s3-to-redshift to allow multiple syncs to run per day (and to refresh new data within a certain time range, specified by `granularity`). These changes:
1. Introduce a `granularity` flag, which determines how often we expect to store copies of data in each table. Currently, this is a daily interval for all tables involved.
2. Modify the `--force` conditions to allow updates to the most recent sync for new, incoming data (i.e. in the current day, or hour, depending on `granularity`).
3. Introduce an extra step in the SQL transaction (`TruncateInTimeRange`) that, for a particular sync, deletes data before …

IP-737: Replace matching data within time range

---

Dockerfile

You were assigned as the most active recent contributor to this repo or because Nate didn't want to assign the PR to himself.
Additional context on this can be found on the [DISTRICTS-364](https://clever.atlassian.net/browse/DISTRICTS-364) ticket.
Please reassign and share the joy of gearcmd if needed, or ask @natebrennand in #oncall-districts if you have any questions.

update gearcmd to v0.7.0

---

README.md

Nearly everything is deployed by ark now.
Context:
- https://clever.atlassian.net/browse/INFRA-1718

Updated production deploy command

---

.drone.yml
launch/s3-to-redshift-fast.yml

**[Associated SALT PR](https://github.com/Clever/salt/pull/2191/files)**
**Overview:**
Add configuration to publish a duplicate `s3-to-redshift-fast-prod` worker

Publish to a "fast" worker

---

Dockerfile
launch/s3-to-redshift-fast.yml
launch/s3-to-redshift.yml

**[Associated SALT PR](https://github.com/Clever/salt/pull/2193)**

Include WORKER_NAME for publishing to gearman

---

Dockerfile

Fix Dockerfile cmd

---

.github/pull_request_template.md

**JIRA**: N/A
**Overview**: Updates the PR template to include reminder to deploy both `s3-to-redshift` and `s3-to-redshift-fast`
**Testing**: N/A
**Roll Out**: N/A

Include fast-prod instructions in template

---

Dockerfile

I copied the kvconfig.yml to the wrong place :(
*Roll Out*:

Fix Dockerfile issue

---

main.go

**JIRA**: Related to https://clever.atlassian.net/browse/IP-1211
**Overview**: We are logging worker finished events to SignalFx but the dimensionality is still way too high (https://app.signalfx.com/#/catalog/CE_IsqUAcAE?topicFilterType=MetricTimeSeries&select=MetricTimeSeries:Cz_aKf1AgAU). This is because our payloads contain date information. This PR removes the non-essential information that we'd like to not group by.
**Testing**: Ran locally, verified output.
**Roll Out**:

Selectively log payload on job finish

---

redshift/redshift.go

**JIRA**:
**Overview**:
**Testing**:
**Roll Out**:

Add date (without time) type from redshift.

---

redshift/redshift.go
redshift/redshift_test.go

Reverts Clever/s3-to-redshift#92, until we decide if "Truncate" is the right move here

Revert "Truncate like we mean it"

---

redshift/redshift.go

The input to the Mongo schema is json files, so the ordering doesn't
actually matter.
**JIRA**:
**Overview**:
**Testing**:
**Roll Out**:

Don't check for column ordering if schema is mongo

---

.github/pull_request_template.md
README.md
circle.yml

Also remove deploy instructions that aren't really relevant any more
**JIRA**:
**Overview**:
**Testing**:
**Roll Out**:

Auto deploy

---

.gitignore
Dockerfile
Gopkg.lock
Makefile
golang.mk
launch/s3-to-redshift-fast.yml
launch/s3-to-redshift.yml
sfncli.mk

**JIRA**: https://clever.atlassian.net/browse/INFRA-2786

convert to sfncli

---

launch/s3-to-redshift.yml

remove aws credentials in favor of role

---

launch/s3-to-redshift.yml

**JIRA**:
**Overview**:
**Testing**:
**Roll Out**:

Add access to s3 long-term metrics

---

redshift/redshift.go

**Jira:**
https://clever.atlassian.net/browse/IP-1944
**Overview:**
refer to ticket

ping db to validate connection

---

launch/s3-to-redshift.yml

refer to ticket for full context: https://clever.atlassian.net/browse/IPOC-982

autoscaling params

---

Gopkg.toml
golang.mk

Fix master

---

Gopkg.lock
Gopkg.toml
main.go

**JIRA**:
**Overview**:
**Testing**:
**Roll Out**:

Migrate to using workerutil.analyticspipeline for config.

---

s3filepath/s3filepath.go
s3filepath/s3filepath_test.go

Passion project Wednesday.
Our clever-analytics bucket is a terrible mess.
This puts data into descriptive subfolders for better processing, potentially included with spectrum later on.
I have a script to migrate data, but that comes after the deploy/confirmation this is working.

S3 data is default read from subfolders.

---

Makefile
launch/s3-to-redshift.yml
main.go

Reverts Clever/s3-to-redshift#134
Seeing a lot of:
```
Scanned a large number of deleted rows
```
from `stl_alert_event_log`

Revert "Remove call to redshift-vacuum"

---

redshift/redshift.go
redshift/redshift_test.go

**JIRA**:
[https://clever.atlassian.net/browse/IL-1318](url)
**Overview**:
Adding support for bigint field type.
**Testing**:
Added test case for bigint column adding.
**Roll Out**:

Support for bigint

---

redshift/redshift.go
redshift/redshift_test.go

**JIRA**:
**Overview**:
**Testing**:
**Roll Out**:

Fix incorrect range query.

---

main.go

I recommend turning off whitespace diffs on this one.

All jobs should kick off a vacuum - e.g. streams, at minimum a delete.

---

redshift/redshift.go
redshift/redshift_test.go

since we aren't creating new tables the compupdate flag doesn't give us any benefits

remove compupdate flag

---

Gopkg.lock

**JIRA**:
**Overview**:
**Testing**:
**Roll Out**:

Upgrade pq lib for better cancelling.

---

Makefile
launch/s3-to-redshift.yml
main.go

**JIRA**:
**Overview**:
**Testing**:
**Roll Out**:

New vacuum/analyze argument format.

---

main.go

**JIRA**:
**Overview**:
**Testing**:
**Roll Out**:

Fix cleanup parameter name.

---

main.go

**JIRA**:
**Overview**:
**Testing**:
**Roll Out**:

Fix format

---

Gopkg.lock
Gopkg.toml

for https://github.com/Clever/analytics-util/pull/9

bump analytics-util to 1.2.0

---

launch/s3-to-redshift.yml

https://github.com/Clever/ark-config/pull/2224 for context

Remove WORKER_NAME

---

main.go
redshift/redshift.go

**JIRA**:
**Overview**:
**Testing**:
**Roll Out**:

mongo to mongo_raw

---

redshift/redshift.go

There's something funky when we do this outside of the transaction and there isn't already a row in the table, or it's set to null.
Doing it inside the transaction seems to work, and in general this lookup/update should be fast, so it doesn't really matter either way.

Placate the redshift gods and run the select latency in the transaction.

---

redshift/redshift.go

**JIRA**:
**Overview**:
**Testing**:
**Roll Out**:

Optimize latency insert/lookup.

---

redshift/redshift.go

Update latency write to be outside the transaction, because of Redshift issues.

---

main.go

This should really only be used in conjunction with job debouncing.
**JIRA**:
https://clever.atlassian.net/browse/DEIP-171
**Overview**:
Hot on the tail of https://github.com/Clever/connections-to-s3/pull/104
Now that it works, we can add debouncing to other services.
s3-to-redshift needs to have an arg from the debouncing, so it knows when a load would be invalid,
so this has to merge before the mongo-to-s3 or record-keeper jobs.
**Testing**:
**Roll Out**:

Add support for skipping loads.

---

launch/s3-to-redshift-key-metrics.yml
launch/s3-to-redshift.yml

**JIRA**:
**Overview**:
**Testing**:
**Roll Out**:

Rename eng-ip to eng-deip
