.drone.yml
Makefile
mixpanel/mixpanel_export_test.go
redshift/redshift.go
redshift/redshift_test.go

If the destination table hasn't yet been created in Redshift, you
don't need to drop it. This failure to drop causes and error
and causes the github.com/clever/postgres-to-redshift to fail
on initial import (data gets imported but only to 'temp' table
name)

redshift: drop table if exists

---

redshift/redshift.go
redshift/redshift_test.go

Rename does not allow setting the schema in the new name.
Tested: Ran the actual command.

Fix the ALTER TABLE command when refreshing redshift tables

---

redshift/redshift.go
redshift/redshift_test.go

Without the grant query, users no longer have access once a table gets refreshed
Tested: Unit tests and ran the query locally.

Grant select and references priviliges to public after refresh

---

redshift/redshift.go
redshift/redshift_test.go

Running a full vacuum on the entire redshift database is an very expensive query. This changes redshifter to run a vacuum and analyze on a specific table as the last step of a refresh.
Tested: Unit tests.

Vacuum analyze each individual table after refresh

---

Makefile
cmd/mixpanel_to_redshift.go
mixpanel_to_redshift.go
redshift/README.md
redshift/redshift.go
redshift/redshift_test.go

Closing #16 and #17 in favor of this one.
Big changes, mostly moving to golang sql library transactions instead of our poor-man's transactions :)
The only weird thing here is the `s3Info` struct, don't worry about that one @agclever and @bstein-clever , the PR when I modify for `s3-to-redshift` will have a different way of handling it that will probably make you happy.

Modify redshifter before including s3-to-redshift work

---

s3filepath/s3filepath.go
s3filepath/s3filepath_test.go

Needed to make sure we didn't pick up on the config file if the config name happened to match the prefix of the data.
for instance:
`mongo_sis_config_x.yml`
`mongo_students_x.yml`
was working fine, but:
`mongo_apprequests_config_x.yml`
`mongo_apprequests_x.yml`
was confusing s3-to-redshift.

Fix copy from create table

---

redshift/README.md
redshift/redshift.go
redshift/redshift_test.go

This was me being a little overzealous. Since we don't use CSV copying
anymore, just JSON, ordering the columns is no longer needed.
Ensuring column order is just too strict.

IP-372 Remove ordinal check

---

redshift/redshift.go
s3filepath/s3filepath.go

This will just actually error when we hit the limit - we should figure out a better way to do this, but for now I've deleted some old files to get us under the limit.
I think we should store longer copies of the data for later processing in some smart way - right now we can only keep around about a month's worth of data before querying hits the 1000 item limit, and in any case that gets awkward over 1000 generally
Linked in the code, docs about 1000: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html

Fix date issue

---

Dockerfile

ideally this will take less time, but until we figure out how to address the issue, let's increase the timeout to 2 hours

increase gearcmd timeout for data copy

---

Dockerfile

Reverts Clever/s3-to-redshift#42
This didn't help, and I'd prefer the shorter timeout.
We're opening a ticket with Amazon about why this is failing, instead.

Revert "increase gearcmd timeout for data copy"

---

cmd/s3_to_redshift.go

Reverts Clever/s3-to-redshift#47
Turns out this breaks multiple tables and anyways is not helping, so I'm simply reverting.

Revert "Related to IP-518- close the db session properly"

---

cmd/s3_to_redshift.go
redshift/redshift.go
redshift/redshift_test.go
s3filepath/s3filepath.go
s3filepath/s3filepath_test.go

We need to support manifest files once the data gets above ~500 MB (compressed)
This adds manifest file support and gives more control over gzip, as well as makes some improvements to the tests.

Support manifest files

---

Dockerfile

Based on runs from last week and today we shouldn't need more than 90 mins to run the initial copy command and analyze command (and the first command may not be needed more than once!)
https://www.dropbox.com/s/f0n91susxgsqfih/Screenshot%202016-04-11%2017.23.59.png?dl=0

Increase timeout to 90m

---

launch/s3-to-redshift.yml

Updated resource allocations based on metrics from the past week.
Memory across both services and workers was adjusted to accommodate the max usage seen.  Additional head room was given to apps that hit their max-memory.
CPU for services and workers was adjusted differently from one another.  For workers, CPU allocation was set to a value between the 90<sup>th</sup> and 100<sup>th</sup> percentile.  CPU for services, on the other hand, was set to be slightly above their max usage.
The data these changes were based is linked below.  Please take a look to confirm the new values: https://docs.google.com/spreadsheets/d/14ReGEtZz5oCKaQ6frCqtSH_yW8nBsHRO07miJZDjTTo/edit#gid=0
Finally the team name was added to the launch yaml.
This PR was created programmatically and assigned randomly.  Feel …

Updated s3-to-redshift's resource allocations and team name

---

redshift/redshift.go
redshift/redshift_test.go

We need a longer `longtext` for some of the use cases we are considering. Discussed with @schimmy and he recommended modifying the existing `longtext` instead of adding another one, since `longtext` is not widely used right now.

increasing size of longtext to be really long

---

README.md
redshift/redshift.go
redshift/redshift_test.go
s3_to_redshift.go
s3filepath/s3filepath.go
s3filepath/s3filepath_test.go

**Overview:**
We want to support CSV files for our `COPY` commands, specifically because we need to ingest data which was `UPLOAD`ed, and that command only supports CSV
**Testing:**
Tested locally, having trouble testing that the JSON stuff still works however
**Roll Out:**
Simple rollout as it's idempotent

Ip 847 allow csv with delimiters

---

launch/s3-to-redshift.yml
s3_to_redshift.go

This dynamically determines the AWS region instead of requiring it as an input.
Tested by running locally and ensuring the correct region is selected.

Find Region From Bucket

---

launch/s3-to-redshift.yml

We want to keep this required in case we need to roll back the change made [here](https://github.com/Clever/s3-to-redshift/pull/70).

Add back in Region requirement in launch

---

redshift/redshift.go
redshift/redshift_test.go

**Overview**
Sometimes a column will have spaces in their name. To handle this we need quotes around the name in the CREATE statement.

Add quotes around name for create

---

Dockerfile

**JIRA**: https://clever.atlassian.net/browse/IP-1002 (oncall)
**Overview**: Update `s3-to-redshift` to the latest version of `gearcmd`. This will be useful for `heartbeat` logging, which can notify us when long-running jobs are running so that we can debug live.
**Testing**: See: https://github.com/Clever/gearcmd/pull/50
**Roll Out:**
Remember to revert the .drone.yml change
CC: Assigning you @bstein-clever since Schimmy is busy AFAICT

Bump gearcmd version

---

.drone.yml

Context:  https://clever.atlassian.net/browse/INFRA-1577
Refactor so that report-card is invoked via a Publish block;
this lets Drone do the heavy-lifting instead of setting it up locally.
Expected changes:
- ADDED
- A single entry in the "publish" block `report_card: {}` (if this wasn't already present)
- REMOVED
- All "env" block entries related to report-card are removed
- All "script" block entries related to report-card are removed
- MODIFIED
- YAML reformatting/linting (side-effect)
**Please verify by looking at the build logs**
1. Your build ran successfully (all tests and script steps completed)
2. Report card ran successfully (you can see it in the
If you see any errors in the above, please loop @nathanleiby (@n on Slack) into the PR.
Thanks!

Simpler report-card invocation: s3-to-redshift

---

kvconfig.yml

**JIRA**: Oncall, N/A
**Overview**: Previously we weren't routing the worker name to SignalFx correctly since `function` appears to now be logged as `source` by Kayvee. We want to be able to alert on both payload and worker name!
**Testing**: Verified that the routed logs now contain the worker name.
**Roll Out**:

Route worker name correctly

---

redshift/redshift.go
redshift/redshift_test.go

**JIRA**: https://clever.atlassian.net/browse/IPOC-268
**Overview**: Truncate is necessary since it won't require a VACUUM afterwards. (`DELETE FROM` leaves "deleted rows" lying around in Redshift which adversely affects query performance)
**Testing**:
**Roll Out**:

Truncate like we mean it

---

circle.yml

*Risk rating*: 1 clever clover :four_leaf_clover:  
*or* 0.1 oauth deploys :shipit:
So free to merge yourself
After much discussion, it seems worthwhile to enable docker builds on all branches.  It's always been difficult to deploy development branches to dev.  Which is kinda ironic.  Don't you think? It's like ten thousands tests when all you need is a deploy.  It's like breaking the build by merging to master.  Isn't it ironic?  It's a little too ironic.  I really do think.
Once merged, you'll be able to run `ark start Clever/s3-to-redshift -b <branch>` on a whim.  No more "temporary" changes to [circle.yml](https://github.com/Clever/app-view-service/commit/dbcf816fd208ac42b2821b831b0297978dc6526c#diff-29944324a3cbf9f4bd0162dfe3975d88).  After this PR, you'll live in a world free of …

Enabling docker builds on all branches for Clever/s3-to-redshift

---

main.go
redshift/redshift.go
redshift/redshift_test.go

This PR does two things:
1. Handles an empty table in this worker
2. Runs vacuum / analyze on the table if we truncated it. We could be a bit more aggressive and do these even when we don't truncate the whole table, but I figure it's better to start conservative.
Theoretically after we merge this we could remove some of the redshift-respawn jobs that vacuum tables like mongo.students.
Tested by running locally against the dev cluster.
**JIRA**:
**Overview**:
**Testing**:
**Roll Out**:

Vacuum / analyze after truncating

---

Godeps/Godeps.json
main.go
redshift/redshift.go
redshift/redshift_test.go
vendor/github.com/hashicorp/errwrap/LICENSE
vendor/github.com/hashicorp/errwrap/README.md
vendor/github.com/hashicorp/errwrap/errwrap.go
vendor/github.com/hashicorp/go-multierror/.travis.yml
vendor/github.com/hashicorp/go-multierror/LICENSE
vendor/github.com/hashicorp/go-multierror/Makefile
vendor/github.com/hashicorp/go-multierror/README.md
vendor/github.com/hashicorp/go-multierror/append.go
vendor/github.com/hashicorp/go-multierror/flatten.go
vendor/github.com/hashicorp/go-multierror/format.go
vendor/github.com/hashicorp/go-multierror/multierror.go
vendor/github.com/hashicorp/go-multierror/prefix.go
vendor/github.com/hashicorp/go-multierror/scripts/deps.sh

For now that means erroring with a clear message, so we don't accidentally screw things up, and so that we can fix the issue quickly.
Since view-materializer + s3-to-redshift together assume that the columns are the same (and in the same order) in both the source and the destination.  If the source just has new columns we add them. Otherwise we note the errors and fail.
This change also makes us continue after a single failure, so one bad table config doesn't stop us from loading any data.
**JIRA**:
**Overview**:
**Testing**:
**Roll Out**:

Handle column reorder

---

logger/logger_test.go
main.go

**JIRA**: N/A, oncall idea
**Overview**: Our alerting by payload has been broken for ages :/. Alisha had an idea to trim the payloads we send to SignalFx so that they don't include information we don't care about.
Starting with just schema for now, can expand to add more fields as needed.
**Testing**:
**Roll Out**:

Alert by schema only

---

main.go
redshift/redshift.go
redshift/redshift_test.go

**JIRA**:
https://clever.atlassian.net/browse/IP-1532
**Overview**:
If you want to pull from a view and materialize into a table, for instance, you won't get a sort or distkey. This change enforces creating a table with a sort & distkey, and also relaxes the constraint that the destination table must have the same sortkey & distkey _as long as the source table has no sort or distkey_

Allow ignore of sortkey and distkey

---

Makefile
README.md
main.go
main_test.go
redshift/redshift.go
redshift/redshift_test.go

Now that we support granularity = 'stream' (see https://github.com/Clever/record-keeper/pull/28) we need to support making that idempotent. That means adding start / end dates instead of just granularities to the payload. That way we can delete all the day in the time range before adding the new rows.
**JIRA**:
**Overview**:
**Testing**:
**Roll Out**:

Add support for streaming payloads

---

main.go

**JIRA**: N/A, oncall.
**Overview**: Turns out we weren't actually surrounding our table names with double quotes after all - Golang's os.Args requires double quotes to be escaped. (A simple way to verify this is to write a dummy program and test out how it parses your string arguments by using `flags.Parse()` or printing out `os.Args[1:]`).
**Testing**: Discovered as part of https://github.com/Clever/redshift-vacuum/pull/8
**Roll Out**:

Escape quotes in argument to redshift-vacuum

---

README.md
main.go
main_test.go

Please view commit by commit
**JIRA**: https://clever.atlassian.net/browse/IP-1551
**Overview**: Extends s3-to-redshift to allow treating Redshift timestamps (without timezone) as PST timestamps. This ultimately allows us to implement EOD as midnight PST for historical tables by simply changing the data date column to `_record_timestamp_in_pst` for non-streaming `record-keeper` jobs (to be implemented).
**Testing**:
**Roll Out**:

IP-1556: Add support for EOD in PST

---

Dockerfile

Now that we want to pull user app connections from mongo-to-s3 we have to increase this timeout since it's timing out
**JIRA**:
**Overview**:
**Testing**:
**Roll Out**:

Increase timeout for student_app_connections

---

Dockerfile

This parameter no longer does anything.  Warnings are trimmed to three by gearman-admin:
https://github.com/Clever/gearman-admin/blob/03f2995bc381f0fd5452ec840d5bf2f2ebf7db78/lib/mongodb.js#L63
Removed in an effort to migrate off of gearman: https://docs.google.com/document/d/1bqMTEfHXXqFMu-kFftS3hLZoqW3FPTUq2FzcU02BO38/edit

Removed --warningLength gearcmd parameter

---

main.go

This is part of a series of Redshift cluster health updates
**Overview**:
Since we essentially do a full table replacement we should do a full vacuum and analyze since we don't have guarantees about inserting in sorted order
**Testing**:
🔢 
**Roll Out**:

Change redshift-vacuum command: delete -> analyze

---

Gopkg.lock
main.go
redshift/redshift.go
redshift/redshift_test.go

**JIRA**:
https://clever.atlassian.net/browse/IPOC-738
**Overview**:
Similar to: https://github.com/Clever/redshift-vacuum/pull/19.
Let's make sure to clean up in flight queries, etc in case of a clean exit
Note: updating the datadog `sqlmock` makes this entire thing explode 👎. We might want to revisit this in the future if we have bandwidth
**Testing**:
Updated them 👍 
**Roll Out**:

Handle OS Signals Better

---

main.go

**JIRA**:
https://clever.atlassian.net/browse/IP-2009
**Overview**:
Some `redshift-to-postgres` jobs may be part of a workflow and need some output printed to initiate the next job. Adds logic to determine the right payload to print based on the input table.
**Testing**:
Check that unsupported tables do not output the payload
https://clever-dev--hubble.int.clever.com/s3-to-redshift:master/workflows/w/07cd5097-4a6d-4c54-a2ff-9cba670a58da/jobs
**Roll Out**:

Print payload for redshift-to-postgres on supported tables

---

main.go

**Overview**:
I don't think this bucket that was set as the default actually exists. If you don't specify a bucket, it throws an error because it is unable to determine the region for it. By making it required, it will instead error because of that.
**Testing**: 💯 
**Roll Out**:

Removed default bucket value and made input required

---

Makefile
launch/s3-to-redshift.yml
main.go

Redshift has introduced a lot of features to automate vacuum processes.
We don't need to explicitly run vacuum full's all the time
https://aws.amazon.com/about-aws/whats-new/2018/12/amazon-redshift-automatic-vacuum/
https://aws.amazon.com/about-aws/whats-new/2019/01/amazon-redshift-auto-analyze/
We also get to remove gearman since we don't need it anymore!
**Roll Out:**
No other changes required. I checked against `go/wfsearch` with:
```
Workflow.workflowDefinition.name:"redshift-vacuum:master" AND NOT Workflow.input:*mongo*
```
There is nothing missing in our current cron job definitions

Remove call to redshift-vacuum

---

launch/s3-to-redshift.yml

**JIRA**: No ticket
**Overview**: This worker is always just stuck at 2 because it's not CPU intensive. We should autoscale depending on the business. Right now it's running a pretty much permanent backlog.
**Testing**: 💯 
**Roll Out**:

Updated autoscaling to active-percent instead of cpu

---

launch/s3-to-redshift.yml

Reverts Clever/s3-to-redshift#137
This ended up not being able to deploy for some reason. Reverting to avoid alerts while infra helps me.

Revert "Updated autoscaling to active-percent instead of cpu"

---

redshift/redshift.go
redshift/redshift_test.go

N.B. I changed the order of checks here, and did a few tests locally, so I'm pretty sure about the various error cases, but it's worth double checking those flows with a second pair of eyes.
It turns out that Redshift doesn't have good optimizations for queries of the form:
`select max(time) from <table>` when `time` is the sort key for the table, as the min/max-chunks on blocks are only used for range reductions, and this query is otherwise a full-table scan. :(
By adding a where clause like so:
`select max(time) from <table> where time > <1 day ago>`
we can get significant performance because we're looking over a smaller range.
Because it's not guaranteed that we always have results in a specific time range (failed jobs, infrequent firehose logs, etc.) we do multiple passes on …

Use max query and reduced range scan for more optimized last-value searches.

---

launch/s3-to-redshift.yml

**JIRA**:
**Overview**:
**Testing**:
**Roll Out**:

Gearmand is dead - remove the dependency, or deploys break.

---

redshift/redshift.go
redshift/redshift_test.go

**JIRA**: No JIRA
**Overview**:
Changed map key lookup to iteration looking at the destination table name instead of just the config key. 
We've had a couple of instances lately of people trying to set up mongo-to-redshift jobs and running into the issue that, under the current system, the config key has to be the same as the destination table name in order for the workflow to do its thing. I believe this strict (and incorrect) lookup to be the culprit. Example failure: https://production--hubble.int.clever.com/mongo-to-redshift:master/workflows/w/a824301f-6748-4d33-a0d9-126403456a42/jobs
**Testing**: 😬 
**Roll Out**:

Look up configs by table name

---

main.go

**JIRA**:
https://clever.atlassian.net/browse/IPOC-1345
**Overview**:
`redshift-cleanup` already defaults to vacuum full (so we were running it all the time regardless, but this will make it more explicit. hmlfvs analyze was taking up to a hour at some points and we run it every hour, so it clogs up the pipeline.
Also, truncate would naturally hit a 100% threshold anyway so this really just makes it so we skip extra analyzes that might not be necessary. (we analyze schemas at 0.001% every day already).
Related to https://github.com/Clever/redshift-cleanup/pull/44
Alternatively, we can make the non-truncate skip analyzing

Add thresholds for analyze

---

redshift/redshift.go

The problem: I'm adding more constraints (uniqueness, foreign keys, etc) to our tables, which is causing things to get messed up. This is because our query currently does a poor join, and rows for keys would get duplicated if there were multiple constraints for that column. This fixes that.
Before:
```
name       |          col_type           | default_val | not_null | primary_key | dist_key | sort_
-----------------+-----------------------------+-------------+----------+-------------+----------+------
_data_timestamp | timestamp without time zone |             | f        | f           | f        |      
id              | character varying(256)      |             | t        | f           | f        |      
id              | character varying(256)      |             | t        | t …
```

Update table metadata query to allow for the primary key to be involved in other constraints.

---

.circleci/config.yml
launch/s3-to-redshift-key-metrics.yml

**Overview**: Hoping to have some workflows avoid the long s3-to-redshift queue, much like we do with some rtp steps using redshift-to-postgres-key-metrics.
Goes with https://github.com/Clever/ark-config/pull/2742

Create new s3-to-redshift-key-metrics resource

---

launch/s3-to-redshift-key-metrics.yml
launch/s3-to-redshift.yml

**JIRA:** https://clever.atlassian.net/browse/INFRANG-5056
**Overview:**
In this PR we will migrate all workers in this repo to use app mesh. We are migrating this worker to mesh_only state directly instead of hybrid as workers don't have albs and hybrid state is not valid for them.
After this PR is merged the workers will start running with a envoy proxy sidecar which will handle all the networking. As applications haven't been migrated to the mesh yet, this change should not cause a significant difference.
**Rollout:**
- Workers have no upstreams so nothing to do here other than merge PR and monitor dapple deploy
- monitor cpu and memory

migrate workers to app mesh in mesh_only state in dev
